[2024-06-24T19:06:19.875+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-24T19:06:19.912+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Stage_1.kafka_producer manual__2024-06-24T19:06:18.071600+00:00 [queued]>
[2024-06-24T19:06:19.924+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Stage_1.kafka_producer manual__2024-06-24T19:06:18.071600+00:00 [queued]>
[2024-06-24T19:06:19.924+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-24T19:06:19.940+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): kafka_producer> on 2024-06-24 19:06:18.071600+00:00
[2024-06-24T19:06:19.948+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=246) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-24T19:06:19.949+0000] {standard_task_runner.py:63} INFO - Started process 247 to run task
[2024-06-24T19:06:19.948+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Stage_1', 'kafka_producer', 'manual__2024-06-24T19:06:18.071600+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/kafka_dag.py', '--cfg-path', '/tmp/tmpo_2g5m3u']
[2024-06-24T19:06:19.950+0000] {standard_task_runner.py:91} INFO - Job 34: Subtask kafka_producer
[2024-06-24T19:06:19.965+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-24T19:06:20.004+0000] {task_command.py:426} INFO - Running <TaskInstance: Stage_1.kafka_producer manual__2024-06-24T19:06:18.071600+00:00 [running]> on host b52dbab8fc24
[2024-06-24T19:06:20.106+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Stage_1' AIRFLOW_CTX_TASK_ID='kafka_producer' AIRFLOW_CTX_EXECUTION_DATE='2024-06-24T19:06:18.071600+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-24T19:06:18.071600+00:00'
[2024-06-24T19:06:20.107+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-24T19:06:20.124+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-24T19:06:20.124+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/kafka_scripts.py", line 17, in kafka_producer_script
    files = os.listdir(directory_path)
            ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-06-24T19:06:20.135+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Stage_1, task_id=kafka_producer, run_id=manual__2024-06-24T19:06:18.071600+00:00, execution_date=20240624T190618, start_date=20240624T190619, end_date=20240624T190620
[2024-06-24T19:06:20.148+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 34 for task kafka_producer (name 'os' is not defined; 247)
[2024-06-24T19:06:20.163+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-24T19:06:20.182+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-24T19:06:20.184+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
