[2024-07-01T19:25:39.766+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-01T19:25:39.837+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: purchase_dag.run_pyspark_job manual__2024-07-01T19:25:38.644509+00:00 [queued]>
[2024-07-01T19:25:39.861+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: purchase_dag.run_pyspark_job manual__2024-07-01T19:25:38.644509+00:00 [queued]>
[2024-07-01T19:25:39.862+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-01T19:25:39.896+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): run_pyspark_job> on 2024-07-01 19:25:38.644509+00:00
[2024-07-01T19:25:39.911+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=258) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-01T19:25:39.913+0000] {standard_task_runner.py:63} INFO - Started process 259 to run task
[2024-07-01T19:25:39.921+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'purchase_dag', 'run_pyspark_job', 'manual__2024-07-01T19:25:38.644509+00:00', '--job-id', '531', '--raw', '--subdir', 'DAGS_FOLDER/purchase_dag.py', '--cfg-path', '/tmp/tmpvrr5lexb']
[2024-07-01T19:25:39.925+0000] {standard_task_runner.py:91} INFO - Job 531: Subtask run_pyspark_job
[2024-07-01T19:25:39.956+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-01T19:25:40.023+0000] {task_command.py:426} INFO - Running <TaskInstance: purchase_dag.run_pyspark_job manual__2024-07-01T19:25:38.644509+00:00 [running]> on host 0a37133e4d82
[2024-07-01T19:25:40.220+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='purchase_dag' AIRFLOW_CTX_TASK_ID='run_pyspark_job' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T19:25:38.644509+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-01T19:25:38.644509+00:00'
[2024-07-01T19:25:40.221+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-01T19:25:40.278+0000] {docker.py:366} INFO - Starting docker container from image bitnami/spark:latest
[2024-07-01T19:25:40.283+0000] {docker.py:374} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-07-01T19:25:40.788+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m19:25:40.78 [0m[38;5;2mINFO [0m ==>
[2024-07-01T19:25:40.790+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m19:25:40.78 [0m[38;5;2mINFO [0m ==> [1mWelcome to the Bitnami spark container[0m
[2024-07-01T19:25:40.792+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m19:25:40.79 [0m[38;5;2mINFO [0m ==> Subscribe to project updates by watching [1mhttps://github.com/bitnami/containers[0m
[2024-07-01T19:25:40.794+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m19:25:40.79 [0m[38;5;2mINFO [0m ==> Submit issues and feature requests at [1mhttps://github.com/bitnami/containers/issues[0m
[2024-07-01T19:25:40.795+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m19:25:40.79 [0m[38;5;2mINFO [0m ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit [1mhttps://bitnami.com/enterprise[0m
[2024-07-01T19:25:40.798+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m19:25:40.79 [0m[38;5;2mINFO [0m ==>
[2024-07-01T19:25:40.806+0000] {docker.py:436} INFO - 
[2024-07-01T19:25:44.006+0000] {docker.py:436} INFO - python3: can't open file '/opt/bitnami/spark/scripts/load_bronze_table.py': [Errno 2] No such file or directory
[2024-07-01T19:25:44.024+0000] {docker.py:436} INFO - 24/07/01 19:25:44 INFO ShutdownHookManager: Shutdown hook called
[2024-07-01T19:25:44.028+0000] {docker.py:436} INFO - 24/07/01 19:25:44 INFO ShutdownHookManager: Deleting directory /tmp/spark-e3c1082c-39d6-4cdc-bb8d-666a97bb7164
[2024-07-01T19:25:44.323+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-01T19:25:44.338+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 265, in _raise_for_status
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://docker-proxy:2375/v1.45/containers/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 371, in _run_image
    return self._run_image_with_mounts([*self.mounts, tmp_mount], add_tmp_variable=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 398, in _run_image_with_mounts
    self.container = self.cli.create_container(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 439, in create_container
    return self.create_container_from_config(config, name, platform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 456, in create_container_from_config
    return self._result(res, True)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 271, in _result
    self._raise_for_status(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 267, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 400 Client Error for http://docker-proxy:2375/v1.45/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /tmp/airflowtmp_6f93is1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 509, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 380, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 444, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 2}
[2024-07-01T19:25:44.347+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=purchase_dag, task_id=run_pyspark_job, run_id=manual__2024-07-01T19:25:38.644509+00:00, execution_date=20240701T192538, start_date=20240701T192539, end_date=20240701T192544
[2024-07-01T19:25:44.373+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 531 for task run_pyspark_job (Docker container failed: {'StatusCode': 2}; 259)
[2024-07-01T19:25:44.401+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-01T19:25:44.433+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-01T19:25:44.438+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
