[2024-06-24T17:44:34.757+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-24T17:44:34.811+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Stage_1.kafka_create_topic manual__2024-06-24T17:44:33.343814+00:00 [queued]>
[2024-06-24T17:44:34.822+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Stage_1.kafka_create_topic manual__2024-06-24T17:44:33.343814+00:00 [queued]>
[2024-06-24T17:44:34.822+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-24T17:44:34.840+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): kafka_create_topic> on 2024-06-24 17:44:33.343814+00:00
[2024-06-24T17:44:34.850+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=207) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-24T17:44:34.851+0000] {standard_task_runner.py:63} INFO - Started process 209 to run task
[2024-06-24T17:44:34.849+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Stage_1', 'kafka_create_topic', 'manual__2024-06-24T17:44:33.343814+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/kafka_dag.py', '--cfg-path', '/tmp/tmpmt98b6dy']
[2024-06-24T17:44:34.852+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask kafka_create_topic
[2024-06-24T17:44:34.868+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-24T17:44:34.906+0000] {task_command.py:426} INFO - Running <TaskInstance: Stage_1.kafka_create_topic manual__2024-06-24T17:44:33.343814+00:00 [running]> on host 505254ae63d4
[2024-06-24T17:44:35.011+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Stage_1' AIRFLOW_CTX_TASK_ID='kafka_create_topic' AIRFLOW_CTX_EXECUTION_DATE='2024-06-24T17:44:33.343814+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-24T17:44:33.343814+00:00'
[2024-06-24T17:44:35.012+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-24T17:44:35.055+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9094 <connecting> [IPv6 ('::1', 9094, 0, 0)]>: connecting to localhost:9094 [('::1', 9094, 0, 0) IPv6]
[2024-06-24T17:44:35.056+0000] {conn.py:1206} INFO - Probing node bootstrap-0 broker version
[2024-06-24T17:44:35.057+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9094 <connecting> [IPv6 ('::1', 9094, 0, 0)]> returned error 111. Disconnecting.
[2024-06-24T17:44:35.057+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9094 <connecting> [IPv6 ('::1', 9094, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-06-24T17:44:35.105+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9094 <connecting> [IPv6 ('::1', 9094, 0, 0)]>: connecting to localhost:9094 [('::1', 9094, 0, 0) IPv6]
[2024-06-24T17:44:35.105+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9094 <connecting> [IPv6 ('::1', 9094, 0, 0)]> returned error 111. Disconnecting.
[2024-06-24T17:44:35.106+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9094 <connecting> [IPv6 ('::1', 9094, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-06-24T17:44:35.155+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9094 <connecting> [IPv4 ('127.0.0.1', 9094)]>: connecting to localhost:9094 [('127.0.0.1', 9094) IPv4]
[2024-06-24T17:44:35.155+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9094 <connecting> [IPv4 ('127.0.0.1', 9094)]> returned error 111. Disconnecting.
[2024-06-24T17:44:35.156+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9094 <connecting> [IPv4 ('127.0.0.1', 9094)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-06-24T17:44:35.156+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-24T17:44:35.156+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/kafka_create_topic.py", line 14, in create_kafka_topic
    admin_client = KafkaAdminClient(bootstrap_servers=bootstrap_servers, client_id='kafka-python-example')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/admin/client.py", line 210, in __init__
    self._client = self.config['kafka_client'](
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py", line 900, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2024-06-24T17:44:35.171+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Stage_1, task_id=kafka_create_topic, run_id=manual__2024-06-24T17:44:33.343814+00:00, execution_date=20240624T174433, start_date=20240624T174434, end_date=20240624T174435
[2024-06-24T17:44:35.187+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 10 for task kafka_create_topic (NoBrokersAvailable; 209)
[2024-06-24T17:44:35.226+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-24T17:44:35.250+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-24T17:44:35.253+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
