[2024-07-02T10:54:16.586+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-02T10:54:16.621+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: purchase_dag.run_pyspark_job manual__2024-07-02T10:54:09.758349+00:00 [queued]>
[2024-07-02T10:54:16.631+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: purchase_dag.run_pyspark_job manual__2024-07-02T10:54:09.758349+00:00 [queued]>
[2024-07-02T10:54:16.631+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-02T10:54:16.646+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): run_pyspark_job> on 2024-07-02 10:54:09.758349+00:00
[2024-07-02T10:54:16.653+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=246) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-02T10:54:16.653+0000] {standard_task_runner.py:63} INFO - Started process 247 to run task
[2024-07-02T10:54:16.653+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'purchase_dag', 'run_pyspark_job', 'manual__2024-07-02T10:54:09.758349+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/purchase_dag.py', '--cfg-path', '/tmp/tmpkilx0tf_']
[2024-07-02T10:54:16.655+0000] {standard_task_runner.py:91} INFO - Job 22: Subtask run_pyspark_job
[2024-07-02T10:54:16.669+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-02T10:54:16.701+0000] {task_command.py:426} INFO - Running <TaskInstance: purchase_dag.run_pyspark_job manual__2024-07-02T10:54:09.758349+00:00 [running]> on host 1bb3b4acd47e
[2024-07-02T10:54:16.786+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='purchase_dag' AIRFLOW_CTX_TASK_ID='run_pyspark_job' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T10:54:09.758349+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-02T10:54:09.758349+00:00'
[2024-07-02T10:54:16.787+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-02T10:54:16.820+0000] {docker.py:366} INFO - Starting docker container from image bitnami/spark:latest
[2024-07-02T10:54:16.824+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-02T10:54:16.825+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 265, in _raise_for_status
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://docker-proxy:2375/v1.45/containers/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 509, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 371, in _run_image
    return self._run_image_with_mounts([*self.mounts, tmp_mount], add_tmp_variable=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 398, in _run_image_with_mounts
    self.container = self.cli.create_container(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 439, in create_container
    return self.create_container_from_config(config, name, platform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 456, in create_container_from_config
    return self._result(res, True)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 271, in _result
    self._raise_for_status(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 267, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 400 Client Error for http://docker-proxy:2375/v1.45/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /home/arun/Desktop/dhaarini/DataEngineer/Projects/DE_Purchase_Tracker/dag")
[2024-07-02T10:54:16.836+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=purchase_dag, task_id=run_pyspark_job, run_id=manual__2024-07-02T10:54:09.758349+00:00, execution_date=20240702T105409, start_date=20240702T105416, end_date=20240702T105416
[2024-07-02T10:54:16.849+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 22 for task run_pyspark_job (400 Client Error for http://docker-proxy:2375/v1.45/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /home/arun/Desktop/dhaarini/DataEngineer/Projects/DE_Purchase_Tracker/dag"); 247)
[2024-07-02T10:54:16.867+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-02T10:54:16.883+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T10:54:16.885+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
