[2024-07-02T19:44:35.738+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-02T19:44:35.773+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: purchase_dag.gold_data_feed manual__2024-07-02T19:43:35.024920+00:00 [queued]>
[2024-07-02T19:44:35.784+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: purchase_dag.gold_data_feed manual__2024-07-02T19:43:35.024920+00:00 [queued]>
[2024-07-02T19:44:35.785+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-02T19:44:35.812+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): gold_data_feed> on 2024-07-02 19:43:35.024920+00:00
[2024-07-02T19:44:35.819+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=423) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-02T19:44:35.820+0000] {standard_task_runner.py:63} INFO - Started process 424 to run task
[2024-07-02T19:44:35.819+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'purchase_dag', 'gold_data_feed', 'manual__2024-07-02T19:43:35.024920+00:00', '--job-id', '140', '--raw', '--subdir', 'DAGS_FOLDER/purchase_dag.py', '--cfg-path', '/tmp/tmpd8z7f057']
[2024-07-02T19:44:35.821+0000] {standard_task_runner.py:91} INFO - Job 140: Subtask gold_data_feed
[2024-07-02T19:44:35.848+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-02T19:44:35.879+0000] {task_command.py:426} INFO - Running <TaskInstance: purchase_dag.gold_data_feed manual__2024-07-02T19:43:35.024920+00:00 [running]> on host c87667283844
[2024-07-02T19:44:35.998+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='purchase_dag' AIRFLOW_CTX_TASK_ID='gold_data_feed' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T19:43:35.024920+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-02T19:43:35.024920+00:00'
[2024-07-02T19:44:35.999+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-02T19:44:36.036+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-02T19:44:36.037+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/gold_data_feed.py", line 27, in gold_data_feed_gen
    with open(file_nme123, 'w', newline='') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/tgt/gold_feed.csv'
[2024-07-02T19:44:36.051+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=purchase_dag, task_id=gold_data_feed, run_id=manual__2024-07-02T19:43:35.024920+00:00, execution_date=20240702T194335, start_date=20240702T194435, end_date=20240702T194436
[2024-07-02T19:44:36.091+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 140 for task gold_data_feed ([Errno 2] No such file or directory: '/opt/airflow/tgt/gold_feed.csv'; 424)
[2024-07-02T19:44:36.117+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-02T19:44:36.135+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T19:44:36.151+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
