[2024-06-24T17:50:45.235+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-24T17:50:45.300+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Stage_1.kafka_create_topic manual__2024-06-24T17:50:44.362685+00:00 [queued]>
[2024-06-24T17:50:45.318+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Stage_1.kafka_create_topic manual__2024-06-24T17:50:44.362685+00:00 [queued]>
[2024-06-24T17:50:45.319+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-24T17:50:45.352+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): kafka_create_topic> on 2024-06-24 17:50:44.362685+00:00
[2024-06-24T17:50:45.362+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=276) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-24T17:50:45.364+0000] {standard_task_runner.py:63} INFO - Started process 279 to run task
[2024-06-24T17:50:45.362+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Stage_1', 'kafka_create_topic', 'manual__2024-06-24T17:50:44.362685+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/kafka_dag.py', '--cfg-path', '/tmp/tmpm5rnjjyr']
[2024-06-24T17:50:45.365+0000] {standard_task_runner.py:91} INFO - Job 12: Subtask kafka_create_topic
[2024-06-24T17:50:45.390+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-24T17:50:45.472+0000] {task_command.py:426} INFO - Running <TaskInstance: Stage_1.kafka_create_topic manual__2024-06-24T17:50:44.362685+00:00 [running]> on host 505254ae63d4
[2024-06-24T17:50:45.639+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Stage_1' AIRFLOW_CTX_TASK_ID='kafka_create_topic' AIRFLOW_CTX_EXECUTION_DATE='2024-06-24T17:50:44.362685+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-24T17:50:44.362685+00:00'
[2024-06-24T17:50:45.641+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-24T17:50:45.658+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-06-24T17:50:45.658+0000] {conn.py:1206} INFO - Probing node bootstrap-0 broker version
[2024-06-24T17:50:45.659+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-06-24T17:50:45.659+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-06-24T17:50:45.707+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-06-24T17:50:45.708+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 111. Disconnecting.
[2024-06-24T17:50:45.708+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-06-24T17:50:45.757+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-06-24T17:50:45.758+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-06-24T17:50:45.758+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-06-24T17:50:45.759+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-24T17:50:45.759+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/kafka_create_topic.py", line 14, in create_kafka_topic
    admin_client = KafkaAdminClient(bootstrap_servers=bootstrap_servers, client_id='kafka-python-example')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/admin/client.py", line 210, in __init__
    self._client = self.config['kafka_client'](
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py", line 900, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2024-06-24T17:50:45.771+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Stage_1, task_id=kafka_create_topic, run_id=manual__2024-06-24T17:50:44.362685+00:00, execution_date=20240624T175044, start_date=20240624T175045, end_date=20240624T175045
[2024-06-24T17:50:45.789+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 12 for task kafka_create_topic (NoBrokersAvailable; 279)
[2024-06-24T17:50:45.831+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-24T17:50:45.856+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-24T17:50:45.858+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
