[2024-06-25T07:47:46.634+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-25T07:47:46.669+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Stage_1.run_pyspark_job manual__2024-06-25T07:47:41.239472+00:00 [queued]>
[2024-06-25T07:47:46.679+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Stage_1.run_pyspark_job manual__2024-06-25T07:47:41.239472+00:00 [queued]>
[2024-06-25T07:47:46.679+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-25T07:47:46.693+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): run_pyspark_job> on 2024-06-25 07:47:41.239472+00:00
[2024-06-25T07:47:46.702+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=237) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-25T07:47:46.703+0000] {standard_task_runner.py:63} INFO - Started process 238 to run task
[2024-06-25T07:47:46.701+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Stage_1', 'run_pyspark_job', 'manual__2024-06-25T07:47:41.239472+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/kafka_dag.py', '--cfg-path', '/tmp/tmpz10zr15h']
[2024-06-25T07:47:46.704+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask run_pyspark_job
[2024-06-25T07:47:46.719+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-25T07:47:46.752+0000] {task_command.py:426} INFO - Running <TaskInstance: Stage_1.run_pyspark_job manual__2024-06-25T07:47:41.239472+00:00 [running]> on host f0fe84c44306
[2024-06-25T07:47:46.845+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Stage_1' AIRFLOW_CTX_TASK_ID='run_pyspark_job' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T07:47:41.239472+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-25T07:47:41.239472+00:00'
[2024-06-25T07:47:46.846+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-25T07:47:46.866+0000] {docker.py:157} ERROR - Failed to establish connection to Docker host unix://var/run/docker.sock: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
[2024-06-25T07:47:46.867+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-25T07:47:46.876+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 492, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 362, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2024-06-25T07:47:46.880+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Stage_1, task_id=run_pyspark_job, run_id=manual__2024-06-25T07:47:41.239472+00:00, execution_date=20240625T074741, start_date=20240625T074746, end_date=20240625T074746
[2024-06-25T07:47:46.892+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task run_pyspark_job (Failed to establish connection to any given Docker hosts.; 238)
[2024-06-25T07:47:46.917+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-25T07:47:46.933+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-25T07:47:46.935+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
