[2024-07-02T11:23:01.666+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-02T11:23:01.703+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: purchase_dag.run_pyspark_job manual__2024-07-02T11:22:53.675290+00:00 [queued]>
[2024-07-02T11:23:01.714+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: purchase_dag.run_pyspark_job manual__2024-07-02T11:22:53.675290+00:00 [queued]>
[2024-07-02T11:23:01.714+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-02T11:23:01.728+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): run_pyspark_job> on 2024-07-02 11:22:53.675290+00:00
[2024-07-02T11:23:01.736+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=558) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-02T11:23:01.737+0000] {standard_task_runner.py:63} INFO - Started process 559 to run task
[2024-07-02T11:23:01.736+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'purchase_dag', 'run_pyspark_job', 'manual__2024-07-02T11:22:53.675290+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/purchase_dag.py', '--cfg-path', '/tmp/tmp7_tzq33s']
[2024-07-02T11:23:01.738+0000] {standard_task_runner.py:91} INFO - Job 32: Subtask run_pyspark_job
[2024-07-02T11:23:01.753+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-02T11:23:01.785+0000] {task_command.py:426} INFO - Running <TaskInstance: purchase_dag.run_pyspark_job manual__2024-07-02T11:22:53.675290+00:00 [running]> on host 1bb3b4acd47e
[2024-07-02T11:23:01.879+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='purchase_dag' AIRFLOW_CTX_TASK_ID='run_pyspark_job' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T11:22:53.675290+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-02T11:22:53.675290+00:00'
[2024-07-02T11:23:01.880+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-02T11:23:01.913+0000] {docker.py:366} INFO - Starting docker container from image bitnami/spark:latest
[2024-07-02T11:23:01.916+0000] {docker.py:374} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-07-02T11:23:02.385+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m11:23:02.38 [0m[38;5;2mINFO [0m ==>
[2024-07-02T11:23:02.386+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m11:23:02.38 [0m[38;5;2mINFO [0m ==> [1mWelcome to the Bitnami spark container[0m
[2024-07-02T11:23:02.388+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m11:23:02.38 [0m[38;5;2mINFO [0m ==> Subscribe to project updates by watching [1mhttps://github.com/bitnami/containers[0m
[2024-07-02T11:23:02.390+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m11:23:02.38 [0m[38;5;2mINFO [0m ==> Submit issues and feature requests at [1mhttps://github.com/bitnami/containers/issues[0m
[2024-07-02T11:23:02.391+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m11:23:02.39 [0m[38;5;2mINFO [0m ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit [1mhttps://bitnami.com/enterprise[0m
[2024-07-02T11:23:02.393+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m11:23:02.39 [0m[38;5;2mINFO [0m ==>
[2024-07-02T11:23:02.401+0000] {docker.py:436} INFO - 
[2024-07-02T11:23:04.730+0000] {docker.py:436} INFO - :: loading settings :: url = jar:file:/opt/bitnami/spark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-07-02T11:23:04.827+0000] {docker.py:436} INFO - Ivy Default Cache set to: /opt/bitnami/spark/.ivy2/cache
The jars for the packages stored in: /opt/bitnami/spark/.ivy2/jars
[2024-07-02T11:23:04.835+0000] {docker.py:436} INFO - org.postgresql#postgresql added as a dependency
org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2024-07-02T11:23:04.837+0000] {docker.py:436} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-372af3df-68dd-42e2-83d9-cd3768720763;1.0
[2024-07-02T11:23:04.837+0000] {docker.py:436} INFO - confs: [default]
[2024-07-02T11:23:12.499+0000] {docker.py:436} INFO - :: resolution report :: resolve 7662ms :: artifacts dl 0ms
[2024-07-02T11:23:12.500+0000] {docker.py:436} INFO - :: modules in use:
[2024-07-02T11:23:12.501+0000] {docker.py:436} INFO - ---------------------------------------------------------------------
[2024-07-02T11:23:12.502+0000] {docker.py:436} INFO - |                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
[2024-07-02T11:23:12.503+0000] {docker.py:436} INFO - |      default     |   2   |   0   |   0   |   0   ||   0   |   0   |
	---------------------------------------------------------------------
[2024-07-02T11:23:12.506+0000] {docker.py:436} INFO - :: problems summary ::
[2024-07-02T11:23:12.506+0000] {docker.py:436} INFO - :::: WARNINGS
		module not found: org.postgresql#postgresql;42.5.4

	==== local-m2-cache: tried

	  file:/opt/bitnami/spark/.m2/repository/org/postgresql/postgresql/42.5.4/postgresql-42.5.4.pom

	  -- artifact org.postgresql#postgresql;42.5.4!postgresql.jar:

	  file:/opt/bitnami/spark/.m2/repository/org/postgresql/postgresql/42.5.4/postgresql-42.5.4.jar

	==== local-ivy-cache: tried

	  /opt/bitnami/spark/.ivy2/local/org.postgresql/postgresql/42.5.4/ivys/ivy.xml

	  -- artifact org.postgresql#postgresql;42.5.4!postgresql.jar:

	  /opt/bitnami/spark/.ivy2/local/org.postgresql/postgresql/42.5.4/jars/postgresql.jar

	==== central: tried

	  https://repo1.maven.org/maven2/org/postgresql/postgresql/42.5.4/postgresql-42.5.4.pom
[2024-07-02T11:23:12.507+0000] {docker.py:436} INFO - -- artifact org.postgresql#postgresql;42.5.4!postgresql.jar:

	  https://repo1.maven.org/maven2/org/postgresql/postgresql/42.5.4/postgresql-42.5.4.jar

	==== spark-packages: tried

	  https://repos.spark-packages.org/org/postgresql/postgresql/42.5.4/postgresql-42.5.4.pom

	  -- artifact org.postgresql#postgresql;42.5.4!postgresql.jar:

	  https://repos.spark-packages.org/org/postgresql/postgresql/42.5.4/postgresql-42.5.4.jar

		module not found: org.apache.spark#spark-sql-kafka-0-10_2.12;3.5.0

	==== local-m2-cache: tried

	  file:/opt/bitnami/spark/.m2/repository/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.0/spark-sql-kafka-0-10_2.12-3.5.0.pom

	  -- artifact org.apache.spark#spark-sql-kafka-0-10_2.12;3.5.0!spark-sql-kafka-0-10_2.12.jar:

	  file:/opt/bitnami/spark/.m2/repository/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.0/spark-sql-kafka-0-10_2.12-3.5.0.jar

	==== local-ivy-cache: tried

	  /opt/bitnami/spark/.ivy2/local/org.apache.spark/spark-sql-kafka-0-10_2.12/3.5.0/ivys/ivy.xml

	  -- artifact org.apache.spark#spark-sql-kafka-0-10_2.12;3.5.0!spark-sql-kafka-0-10_2.12.jar:

	  /opt/bitnami/spark/.ivy2/local/org.apache.spark/spark-sql-kafka-0-10_2.12/3.5.0/jars/spark-sql-kafka-0-10_2.12.jar

	==== central: tried

	  https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.0/spark-sql-kafka-0-10_2.12-3.5.0.pom
[2024-07-02T11:23:12.508+0000] {docker.py:436} INFO - -- artifact org.apache.spark#spark-sql-kafka-0-10_2.12;3.5.0!spark-sql-kafka-0-10_2.12.jar:

	  https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.0/spark-sql-kafka-0-10_2.12-3.5.0.jar

	==== spark-packages: tried

	  https://repos.spark-packages.org/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.0/spark-sql-kafka-0-10_2.12-3.5.0.pom

	  -- artifact org.apache.spark#spark-sql-kafka-0-10_2.12;3.5.0!spark-sql-kafka-0-10_2.12.jar:

	  https://repos.spark-packages.org/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.0/spark-sql-kafka-0-10_2.12-3.5.0.jar

		::::::::::::::::::::::::::::::::::::::::::::::

		::          UNRESOLVED DEPENDENCIES         ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: org.postgresql#postgresql;42.5.4: not found

		:: org.apache.spark#spark-sql-kafka-0-10_2.12;3.5.0: not found

		::::::::::::::::::::::::::::::::::::::::::::::


:::: ERRORS
	Server access error at url https://repo1.maven.org/maven2/org/postgresql/postgresql/42.5.4/postgresql-42.5.4.pom (java.net.SocketException: Network is unreachable)

	Server access error at url https://repo1.maven.org/maven2/org/postgresql/postgresql/42.5.4/postgresql-42.5.4.jar (java.net.SocketException: Network is unreachable)

	Server access error at url https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.0/spark-sql-kafka-0-10_2.12-3.5.0.pom (java.net.SocketException: Network is unreachable)

	Server access error at url https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.0/spark-sql-kafka-0-10_2.12-3.5.0.jar (java.net.SocketException: Network is unreachable)


:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[2024-07-02T11:23:12.509+0000] {docker.py:436} INFO - Exception in thread "main"
[2024-07-02T11:23:12.509+0000] {docker.py:436} INFO - java.lang.RuntimeException: [unresolved dependency: org.postgresql#postgresql;42.5.4: not found, unresolved dependency: org.apache.spark#spark-sql-kafka-0-10_2.12;3.5.0: not found]
	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1608)
	at org.apache.spark.util.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:185)
	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:334)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:964)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:194)
[2024-07-02T11:23:12.510+0000] {docker.py:436} INFO - at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:217)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-07-02T11:23:12.742+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-02T11:23:12.753+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 265, in _raise_for_status
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://docker-proxy:2375/v1.45/containers/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 371, in _run_image
    return self._run_image_with_mounts([*self.mounts, tmp_mount], add_tmp_variable=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 398, in _run_image_with_mounts
    self.container = self.cli.create_container(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 439, in create_container
    return self.create_container_from_config(config, name, platform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 456, in create_container_from_config
    return self._result(res, True)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 271, in _result
    self._raise_for_status(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 267, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 400 Client Error for http://docker-proxy:2375/v1.45/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /tmp/airflowtmppxue4iqk")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 509, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 380, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 444, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2024-07-02T11:23:12.759+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=purchase_dag, task_id=run_pyspark_job, run_id=manual__2024-07-02T11:22:53.675290+00:00, execution_date=20240702T112253, start_date=20240702T112301, end_date=20240702T112312
[2024-07-02T11:23:12.774+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 32 for task run_pyspark_job (Docker container failed: {'StatusCode': 1}; 559)
[2024-07-02T11:23:12.798+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-02T11:23:12.814+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T11:23:12.816+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
