[2024-06-28T15:11:54.191+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T15:11:54.229+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Stage_1.run_silver_job manual__2024-06-28T15:11:01.900256+00:00 [queued]>
[2024-06-28T15:11:54.241+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Stage_1.run_silver_job manual__2024-06-28T15:11:01.900256+00:00 [queued]>
[2024-06-28T15:11:54.241+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-28T15:11:54.258+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): run_silver_job> on 2024-06-28 15:11:01.900256+00:00
[2024-06-28T15:11:54.265+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=189) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-28T15:11:54.267+0000] {standard_task_runner.py:63} INFO - Started process 190 to run task
[2024-06-28T15:11:54.265+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Stage_1', 'run_silver_job', 'manual__2024-06-28T15:11:01.900256+00:00', '--job-id', '442', '--raw', '--subdir', 'DAGS_FOLDER/kafka_dag.py', '--cfg-path', '/tmp/tmp6iwirf85']
[2024-06-28T15:11:54.268+0000] {standard_task_runner.py:91} INFO - Job 442: Subtask run_silver_job
[2024-06-28T15:11:54.286+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-28T15:11:54.323+0000] {task_command.py:426} INFO - Running <TaskInstance: Stage_1.run_silver_job manual__2024-06-28T15:11:01.900256+00:00 [running]> on host 43cb83d08bb6
[2024-06-28T15:11:54.433+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Stage_1' AIRFLOW_CTX_TASK_ID='run_silver_job' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T15:11:01.900256+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-28T15:11:01.900256+00:00'
[2024-06-28T15:11:54.434+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T15:11:54.468+0000] {docker.py:366} INFO - Starting docker container from image bitnami/spark:latest
[2024-06-28T15:11:54.471+0000] {docker.py:374} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-06-28T15:11:54.924+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m15:11:54.92 [0m[38;5;2mINFO [0m ==>
[2024-06-28T15:11:54.926+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m15:11:54.92 [0m[38;5;2mINFO [0m ==> [1mWelcome to the Bitnami spark container[0m
[2024-06-28T15:11:54.927+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m15:11:54.92 [0m[38;5;2mINFO [0m ==> Subscribe to project updates by watching [1mhttps://github.com/bitnami/containers[0m
[2024-06-28T15:11:54.929+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m15:11:54.92 [0m[38;5;2mINFO [0m ==> Submit issues and feature requests at [1mhttps://github.com/bitnami/containers/issues[0m
[2024-06-28T15:11:54.930+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m15:11:54.93 [0m[38;5;2mINFO [0m ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit [1mhttps://bitnami.com/enterprise[0m
[2024-06-28T15:11:54.932+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m15:11:54.93 [0m[38;5;2mINFO [0m ==>
[2024-06-28T15:11:54.940+0000] {docker.py:436} INFO - 
[2024-06-28T15:11:57.188+0000] {docker.py:436} INFO - :: loading settings :: url = jar:file:/opt/bitnami/spark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-06-28T15:11:57.283+0000] {docker.py:436} INFO - Ivy Default Cache set to: /opt/bitnami/spark/.ivy2/cache
The jars for the packages stored in: /opt/bitnami/spark/.ivy2/jars
[2024-06-28T15:11:57.292+0000] {docker.py:436} INFO - org.postgresql#postgresql added as a dependency
[2024-06-28T15:11:57.294+0000] {docker.py:436} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-68a205f2-0711-449c-ba48-c4b9cc41c7cb;1.0
	confs: [default]
[2024-06-28T15:11:59.591+0000] {docker.py:436} INFO - found org.postgresql#postgresql;42.2.2 in central
[2024-06-28T15:11:59.617+0000] {docker.py:436} INFO - downloading https://repo1.maven.org/maven2/org/postgresql/postgresql/42.2.2/postgresql-42.2.2.jar ...
[2024-06-28T15:11:59.725+0000] {docker.py:436} INFO - [SUCCESSFUL ] org.postgresql#postgresql;42.2.2!postgresql.jar(bundle) (119ms)
[2024-06-28T15:11:59.726+0000] {docker.py:436} INFO - :: resolution report :: resolve 2310ms :: artifacts dl 123ms
[2024-06-28T15:11:59.727+0000] {docker.py:436} INFO - :: modules in use:
[2024-06-28T15:11:59.728+0000] {docker.py:436} INFO - org.postgresql#postgresql;42.2.2 from central in [default]
[2024-06-28T15:11:59.728+0000] {docker.py:436} INFO - ---------------------------------------------------------------------
[2024-06-28T15:11:59.729+0000] {docker.py:436} INFO - |                  |            modules            ||   artifacts   |
[2024-06-28T15:11:59.730+0000] {docker.py:436} INFO - |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
[2024-06-28T15:11:59.730+0000] {docker.py:436} INFO - |      default     |   1   |   1   |   1   |   0   ||   1   |   1   |
	---------------------------------------------------------------------
[2024-06-28T15:11:59.732+0000] {docker.py:436} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-68a205f2-0711-449c-ba48-c4b9cc41c7cb
	confs: [default]
[2024-06-28T15:11:59.744+0000] {docker.py:436} INFO - 1 artifacts copied, 0 already retrieved (771kB/11ms)
[2024-06-28T15:12:00.009+0000] {docker.py:436} INFO - 24/06/28 15:12:00 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-06-28T15:12:01.170+0000] {docker.py:436} INFO - 24/06/28 15:12:01 INFO SparkContext: Running Spark version 3.5.1
[2024-06-28T15:12:01.173+0000] {docker.py:436} INFO - 24/06/28 15:12:01 INFO SparkContext: OS info Linux, 6.5.0-41-generic, amd64
24/06/28 15:12:01 INFO SparkContext: Java version 17.0.11
[2024-06-28T15:12:01.204+0000] {docker.py:436} INFO - 24/06/28 15:12:01 INFO ResourceUtils: ==============================================================
[2024-06-28T15:12:01.205+0000] {docker.py:436} INFO - 24/06/28 15:12:01 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-06-28T15:12:01.207+0000] {docker.py:436} INFO - 24/06/28 15:12:01 INFO ResourceUtils: ==============================================================
[2024-06-28T15:12:01.208+0000] {docker.py:436} INFO - 24/06/28 15:12:01 INFO SparkContext: Submitted application: PostgreSQL Connection with PySpark
[2024-06-28T15:12:01.237+0000] {docker.py:436} INFO - 24/06/28 15:12:01 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-06-28T15:12:01.249+0000] {docker.py:436} INFO - 24/06/28 15:12:01 INFO ResourceProfile: Limiting resource is cpu
[2024-06-28T15:12:01.251+0000] {docker.py:436} INFO - 24/06/28 15:12:01 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-06-28T15:12:01.370+0000] {docker.py:436} INFO - 24/06/28 15:12:01 INFO SecurityManager: Changing view acls to: spark
[2024-06-28T15:12:01.371+0000] {docker.py:436} INFO - 24/06/28 15:12:01 INFO SecurityManager: Changing modify acls to: spark
[2024-06-28T15:12:01.372+0000] {docker.py:436} INFO - 24/06/28 15:12:01 INFO SecurityManager: Changing view acls groups to:
[2024-06-28T15:12:01.374+0000] {docker.py:436} INFO - 24/06/28 15:12:01 INFO SecurityManager: Changing modify acls groups to:
[2024-06-28T15:12:01.375+0000] {docker.py:436} INFO - 24/06/28 15:12:01 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: spark; groups with view permissions: EMPTY; users with modify permissions: spark; groups with modify permissions: EMPTY
[2024-06-28T15:12:01.692+0000] {docker.py:436} INFO - 24/06/28 15:12:01 INFO Utils: Successfully started service 'sparkDriver' on port 37039.
[2024-06-28T15:12:01.750+0000] {docker.py:436} INFO - 24/06/28 15:12:01 INFO SparkEnv: Registering MapOutputTracker
[2024-06-28T15:12:01.806+0000] {docker.py:436} INFO - 24/06/28 15:12:01 INFO SparkEnv: Registering BlockManagerMaster
[2024-06-28T15:12:01.844+0000] {docker.py:436} INFO - 24/06/28 15:12:01 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-06-28T15:12:01.845+0000] {docker.py:436} INFO - 24/06/28 15:12:01 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-06-28T15:12:01.850+0000] {docker.py:436} INFO - 24/06/28 15:12:01 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-06-28T15:12:01.874+0000] {docker.py:436} INFO - 24/06/28 15:12:01 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-203b6aff-0565-416c-b64a-756f0e1a8f50
[2024-06-28T15:12:01.893+0000] {docker.py:436} INFO - 24/06/28 15:12:01 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-06-28T15:12:01.917+0000] {docker.py:436} INFO - 24/06/28 15:12:01 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-06-28T15:12:02.097+0000] {docker.py:436} INFO - 24/06/28 15:12:02 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-06-28T15:12:02.193+0000] {docker.py:436} INFO - 24/06/28 15:12:02 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2024-06-28T15:12:02.257+0000] {docker.py:436} INFO - 24/06/28 15:12:02 INFO SparkContext: Added JAR file:///opt/bitnami/spark/.ivy2/jars/org.postgresql_postgresql-42.2.2.jar at spark://localhost:37039/jars/org.postgresql_postgresql-42.2.2.jar with timestamp 1719587521159
[2024-06-28T15:12:02.260+0000] {docker.py:436} INFO - 24/06/28 15:12:02 INFO SparkContext: Added file file:///opt/bitnami/spark/.ivy2/jars/org.postgresql_postgresql-42.2.2.jar at file:///opt/bitnami/spark/.ivy2/jars/org.postgresql_postgresql-42.2.2.jar with timestamp 1719587521159
[2024-06-28T15:12:02.262+0000] {docker.py:436} INFO - 24/06/28 15:12:02 INFO Utils: Copying /opt/bitnami/spark/.ivy2/jars/org.postgresql_postgresql-42.2.2.jar to /tmp/spark-970adcec-2054-4be3-9c7d-32429543ac87/userFiles-1cc3294d-1b0a-42ea-8967-86d6c9ff9ca5/org.postgresql_postgresql-42.2.2.jar
[2024-06-28T15:12:02.403+0000] {docker.py:436} INFO - 24/06/28 15:12:02 INFO Executor: Starting executor ID driver on host localhost
[2024-06-28T15:12:02.406+0000] {docker.py:436} INFO - 24/06/28 15:12:02 INFO Executor: OS info Linux, 6.5.0-41-generic, amd64
24/06/28 15:12:02 INFO Executor: Java version 17.0.11
[2024-06-28T15:12:02.417+0000] {docker.py:436} INFO - 24/06/28 15:12:02 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2024-06-28T15:12:02.418+0000] {docker.py:436} INFO - 24/06/28 15:12:02 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@2b1702e0 for default.
[2024-06-28T15:12:02.436+0000] {docker.py:436} INFO - 24/06/28 15:12:02 INFO Executor: Fetching file:///opt/bitnami/spark/.ivy2/jars/org.postgresql_postgresql-42.2.2.jar with timestamp 1719587521159
[2024-06-28T15:12:02.469+0000] {docker.py:436} INFO - 24/06/28 15:12:02 INFO Utils: /opt/bitnami/spark/.ivy2/jars/org.postgresql_postgresql-42.2.2.jar has been previously copied to /tmp/spark-970adcec-2054-4be3-9c7d-32429543ac87/userFiles-1cc3294d-1b0a-42ea-8967-86d6c9ff9ca5/org.postgresql_postgresql-42.2.2.jar
[2024-06-28T15:12:02.476+0000] {docker.py:436} INFO - 24/06/28 15:12:02 INFO Executor: Fetching spark://localhost:37039/jars/org.postgresql_postgresql-42.2.2.jar with timestamp 1719587521159
[2024-06-28T15:12:02.523+0000] {docker.py:436} INFO - 24/06/28 15:12:02 INFO TransportClientFactory: Successfully created connection to localhost/127.0.0.1:37039 after 31 ms (0 ms spent in bootstraps)
[2024-06-28T15:12:02.531+0000] {docker.py:436} INFO - 24/06/28 15:12:02 INFO Utils: Fetching spark://localhost:37039/jars/org.postgresql_postgresql-42.2.2.jar to /tmp/spark-970adcec-2054-4be3-9c7d-32429543ac87/userFiles-1cc3294d-1b0a-42ea-8967-86d6c9ff9ca5/fetchFileTemp8053694902949647748.tmp
[2024-06-28T15:12:02.559+0000] {docker.py:436} INFO - 24/06/28 15:12:02 INFO Utils: /tmp/spark-970adcec-2054-4be3-9c7d-32429543ac87/userFiles-1cc3294d-1b0a-42ea-8967-86d6c9ff9ca5/fetchFileTemp8053694902949647748.tmp has been previously copied to /tmp/spark-970adcec-2054-4be3-9c7d-32429543ac87/userFiles-1cc3294d-1b0a-42ea-8967-86d6c9ff9ca5/org.postgresql_postgresql-42.2.2.jar
[2024-06-28T15:12:02.565+0000] {docker.py:436} INFO - 24/06/28 15:12:02 INFO Executor: Adding file:/tmp/spark-970adcec-2054-4be3-9c7d-32429543ac87/userFiles-1cc3294d-1b0a-42ea-8967-86d6c9ff9ca5/org.postgresql_postgresql-42.2.2.jar to class loader default
[2024-06-28T15:12:02.579+0000] {docker.py:436} INFO - 24/06/28 15:12:02 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 33565.
[2024-06-28T15:12:02.580+0000] {docker.py:436} INFO - 24/06/28 15:12:02 INFO NettyBlockTransferService: Server created on localhost:33565
[2024-06-28T15:12:02.582+0000] {docker.py:436} INFO - 24/06/28 15:12:02 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-06-28T15:12:02.592+0000] {docker.py:436} INFO - 24/06/28 15:12:02 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, localhost, 33565, None)
[2024-06-28T15:12:02.597+0000] {docker.py:436} INFO - 24/06/28 15:12:02 INFO BlockManagerMasterEndpoint: Registering block manager localhost:33565 with 434.4 MiB RAM, BlockManagerId(driver, localhost, 33565, None)
[2024-06-28T15:12:02.600+0000] {docker.py:436} INFO - 24/06/28 15:12:02 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, localhost, 33565, None)
[2024-06-28T15:12:02.602+0000] {docker.py:436} INFO - 24/06/28 15:12:02 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, localhost, 33565, None)
[2024-06-28T15:12:03.115+0000] {docker.py:436} INFO - 2024-06-28 15:12:03,114:create_spark_session:INFO:Spark session created successfully
[2024-06-28T15:12:03.126+0000] {docker.py:436} INFO - 24/06/28 15:12:03 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2024-06-28T15:12:03.130+0000] {docker.py:436} INFO - 24/06/28 15:12:03 INFO SharedState: Warehouse path is 'file:/opt/bitnami/spark/spark-warehouse'.
[2024-06-28T15:12:05.605+0000] {docker.py:436} INFO - 2024-06-28 15:12:05,605:silver_load:INFO:Load silver table ...
[2024-06-28T15:12:07.163+0000] {docker.py:436} INFO - 24/06/28 15:12:07 INFO CodeGenerator: Code generated in 206.992754 ms
[2024-06-28T15:12:07.296+0000] {docker.py:436} INFO - 24/06/28 15:12:07 INFO DAGScheduler: Registering RDD 3 (jdbc at NativeMethodAccessorImpl.java:0) as input to shuffle 0
[2024-06-28T15:12:07.305+0000] {docker.py:436} INFO - 24/06/28 15:12:07 INFO CodeGenerator: Code generated in 21.075688 ms
[2024-06-28T15:12:07.318+0000] {docker.py:436} INFO - 24/06/28 15:12:07 INFO DAGScheduler: Got map stage job 0 (jdbc at NativeMethodAccessorImpl.java:0) with 1 output partitions
[2024-06-28T15:12:07.319+0000] {docker.py:436} INFO - 24/06/28 15:12:07 INFO DAGScheduler: Final stage: ShuffleMapStage 0 (jdbc at NativeMethodAccessorImpl.java:0)
[2024-06-28T15:12:07.320+0000] {docker.py:436} INFO - 24/06/28 15:12:07 INFO DAGScheduler: Parents of final stage: List()
[2024-06-28T15:12:07.326+0000] {docker.py:436} INFO - 24/06/28 15:12:07 INFO DAGScheduler: Missing parents: List()
[2024-06-28T15:12:07.332+0000] {docker.py:436} INFO - 24/06/28 15:12:07 INFO DAGScheduler: Submitting ShuffleMapStage 0 (MapPartitionsRDD[3] at jdbc at NativeMethodAccessorImpl.java:0), which has no missing parents
[2024-06-28T15:12:07.552+0000] {docker.py:436} INFO - 24/06/28 15:12:07 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 16.7 KiB, free 434.4 MiB)
[2024-06-28T15:12:07.593+0000] {docker.py:436} INFO - 24/06/28 15:12:07 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 8.3 KiB, free 434.4 MiB)
[2024-06-28T15:12:07.596+0000] {docker.py:436} INFO - 24/06/28 15:12:07 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on localhost:33565 (size: 8.3 KiB, free: 434.4 MiB)
[2024-06-28T15:12:07.602+0000] {docker.py:436} INFO - 24/06/28 15:12:07 INFO SparkContext: Created broadcast 0 from broadcast at DAGScheduler.scala:1585
[2024-06-28T15:12:07.623+0000] {docker.py:436} INFO - 24/06/28 15:12:07 INFO DAGScheduler: Submitting 1 missing tasks from ShuffleMapStage 0 (MapPartitionsRDD[3] at jdbc at NativeMethodAccessorImpl.java:0) (first 15 tasks are for partitions Vector(0))
[2024-06-28T15:12:07.625+0000] {docker.py:436} INFO - 24/06/28 15:12:07 INFO TaskSchedulerImpl: Adding task set 0.0 with 1 tasks resource profile 0
[2024-06-28T15:12:07.648+0000] {docker.py:436} INFO - 24/06/28 15:12:07 INFO DAGScheduler: Registering RDD 5 (jdbc at NativeMethodAccessorImpl.java:0) as input to shuffle 1
[2024-06-28T15:12:07.649+0000] {docker.py:436} INFO - 24/06/28 15:12:07 INFO DAGScheduler: Got map stage job 1 (jdbc at NativeMethodAccessorImpl.java:0) with 1 output partitions
[2024-06-28T15:12:07.649+0000] {docker.py:436} INFO - 24/06/28 15:12:07 INFO DAGScheduler: Final stage: ShuffleMapStage 1 (jdbc at NativeMethodAccessorImpl.java:0)
[2024-06-28T15:12:07.650+0000] {docker.py:436} INFO - 24/06/28 15:12:07 INFO DAGScheduler: Parents of final stage: List()
[2024-06-28T15:12:07.651+0000] {docker.py:436} INFO - 24/06/28 15:12:07 INFO DAGScheduler: Missing parents: List()
[2024-06-28T15:12:07.654+0000] {docker.py:436} INFO - 24/06/28 15:12:07 INFO DAGScheduler: Submitting ShuffleMapStage 1 (MapPartitionsRDD[5] at jdbc at NativeMethodAccessorImpl.java:0), which has no missing parents
[2024-06-28T15:12:07.665+0000] {docker.py:436} INFO - 24/06/28 15:12:07 INFO MemoryStore: Block broadcast_1 stored as values in memory (estimated size 14.5 KiB, free 434.4 MiB)
[2024-06-28T15:12:07.670+0000] {docker.py:436} INFO - 24/06/28 15:12:07 INFO MemoryStore: Block broadcast_1_piece0 stored as bytes in memory (estimated size 7.6 KiB, free 434.4 MiB)
[2024-06-28T15:12:07.674+0000] {docker.py:436} INFO - 24/06/28 15:12:07 INFO BlockManagerInfo: Added broadcast_1_piece0 in memory on localhost:33565 (size: 7.6 KiB, free: 434.4 MiB)
[2024-06-28T15:12:07.675+0000] {docker.py:436} INFO - 24/06/28 15:12:07 INFO SparkContext: Created broadcast 1 from broadcast at DAGScheduler.scala:1585
[2024-06-28T15:12:07.676+0000] {docker.py:436} INFO - 24/06/28 15:12:07 INFO DAGScheduler: Submitting 1 missing tasks from ShuffleMapStage 1 (MapPartitionsRDD[5] at jdbc at NativeMethodAccessorImpl.java:0) (first 15 tasks are for partitions Vector(0))
[2024-06-28T15:12:07.677+0000] {docker.py:436} INFO - 24/06/28 15:12:07 INFO TaskSchedulerImpl: Adding task set 1.0 with 1 tasks resource profile 0
[2024-06-28T15:12:07.698+0000] {docker.py:436} INFO - 24/06/28 15:12:07 INFO TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0) (localhost, executor driver, partition 0, PROCESS_LOCAL, 7733 bytes)
[2024-06-28T15:12:07.714+0000] {docker.py:436} INFO - 24/06/28 15:12:07 INFO TaskSetManager: Starting task 0.0 in stage 1.0 (TID 1) (localhost, executor driver, partition 0, PROCESS_LOCAL, 7733 bytes)
[2024-06-28T15:12:07.726+0000] {docker.py:436} INFO - 24/06/28 15:12:07 INFO Executor: Running task 0.0 in stage 1.0 (TID 1)
[2024-06-28T15:12:07.731+0000] {docker.py:436} INFO - 24/06/28 15:12:07 INFO Executor: Running task 0.0 in stage 0.0 (TID 0)
[2024-06-28T15:12:07.921+0000] {docker.py:436} INFO - 24/06/28 15:12:07 INFO CodeGenerator: Code generated in 35.94178 ms
[2024-06-28T15:12:07.955+0000] {docker.py:436} INFO - 24/06/28 15:12:07 INFO CodeGenerator: Code generated in 73.200785 ms
[2024-06-28T15:12:07.995+0000] {docker.py:436} INFO - 24/06/28 15:12:07 INFO CodeGenerator: Code generated in 26.999772 ms
[2024-06-28T15:12:08.002+0000] {docker.py:436} INFO - 24/06/28 15:12:08 INFO CodeGenerator: Code generated in 22.038968 ms
[2024-06-28T15:12:08.080+0000] {docker.py:436} INFO - 24/06/28 15:12:08 INFO JDBCRDD: closed connection
[2024-06-28T15:12:08.182+0000] {docker.py:436} INFO - 24/06/28 15:12:08 INFO Executor: Finished task 0.0 in stage 1.0 (TID 1). 2029 bytes result sent to driver
[2024-06-28T15:12:08.199+0000] {docker.py:436} INFO - 24/06/28 15:12:08 INFO TaskSetManager: Finished task 0.0 in stage 1.0 (TID 1) in 484 ms on localhost (executor driver) (1/1)
[2024-06-28T15:12:08.203+0000] {docker.py:436} INFO - 24/06/28 15:12:08 INFO TaskSchedulerImpl: Removed TaskSet 1.0, whose tasks have all completed, from pool
[2024-06-28T15:12:08.226+0000] {docker.py:436} INFO - 24/06/28 15:12:08 INFO DAGScheduler: ShuffleMapStage 1 (jdbc at NativeMethodAccessorImpl.java:0) finished in 0.568 s
[2024-06-28T15:12:08.229+0000] {docker.py:436} INFO - 24/06/28 15:12:08 INFO DAGScheduler: looking for newly runnable stages
[2024-06-28T15:12:08.231+0000] {docker.py:436} INFO - 24/06/28 15:12:08 INFO DAGScheduler: running: Set(ShuffleMapStage 0)
[2024-06-28T15:12:08.233+0000] {docker.py:436} INFO - 24/06/28 15:12:08 INFO DAGScheduler: waiting: Set()
[2024-06-28T15:12:08.235+0000] {docker.py:436} INFO - 24/06/28 15:12:08 INFO DAGScheduler: failed: Set()
[2024-06-28T15:12:08.297+0000] {docker.py:436} INFO - 24/06/28 15:12:08 INFO JDBCRDD: closed connection
[2024-06-28T15:12:08.322+0000] {docker.py:436} INFO - 24/06/28 15:12:08 INFO Executor: Finished task 0.0 in stage 0.0 (TID 0). 1986 bytes result sent to driver
[2024-06-28T15:12:08.330+0000] {docker.py:436} INFO - 24/06/28 15:12:08 INFO TaskSetManager: Finished task 0.0 in stage 0.0 (TID 0) in 647 ms on localhost (executor driver) (1/1)
[2024-06-28T15:12:08.332+0000] {docker.py:436} INFO - 24/06/28 15:12:08 INFO DAGScheduler: ShuffleMapStage 0 (jdbc at NativeMethodAccessorImpl.java:0) finished in 0.981 s
[2024-06-28T15:12:08.333+0000] {docker.py:436} INFO - 24/06/28 15:12:08 INFO DAGScheduler: looking for newly runnable stages
24/06/28 15:12:08 INFO DAGScheduler: running: Set()
[2024-06-28T15:12:08.334+0000] {docker.py:436} INFO - 24/06/28 15:12:08 INFO DAGScheduler: waiting: Set()
[2024-06-28T15:12:08.334+0000] {docker.py:436} INFO - 24/06/28 15:12:08 INFO DAGScheduler: failed: Set()
[2024-06-28T15:12:08.339+0000] {docker.py:436} INFO - 24/06/28 15:12:08 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool
[2024-06-28T15:12:08.377+0000] {docker.py:436} INFO - 24/06/28 15:12:08 INFO ShufflePartitionsUtil: For shuffle(0, 1), advisory target size: 67108864, actual target size 1048576, minimum partition size: 1048576
[2024-06-28T15:12:08.519+0000] {docker.py:436} INFO - 24/06/28 15:12:08 INFO CodeGenerator: Code generated in 63.125628 ms
[2024-06-28T15:12:08.614+0000] {docker.py:436} INFO - 24/06/28 15:12:08 INFO CodeGenerator: Code generated in 79.806372 ms
[2024-06-28T15:12:08.771+0000] {docker.py:436} INFO - 24/06/28 15:12:08 INFO CodeGenerator: Code generated in 21.431235 ms
[2024-06-28T15:12:08.869+0000] {docker.py:436} INFO - 24/06/28 15:12:08 INFO SparkContext: Starting job: jdbc at NativeMethodAccessorImpl.java:0
[2024-06-28T15:12:08.875+0000] {docker.py:436} INFO - 24/06/28 15:12:08 INFO DAGScheduler: Got job 2 (jdbc at NativeMethodAccessorImpl.java:0) with 1 output partitions
[2024-06-28T15:12:08.880+0000] {docker.py:436} INFO - 24/06/28 15:12:08 INFO DAGScheduler: Final stage: ResultStage 4 (jdbc at NativeMethodAccessorImpl.java:0)
24/06/28 15:12:08 INFO DAGScheduler: Parents of final stage: List(ShuffleMapStage 2, ShuffleMapStage 3)
24/06/28 15:12:08 INFO DAGScheduler: Missing parents: List()
[2024-06-28T15:12:08.882+0000] {docker.py:436} INFO - 24/06/28 15:12:08 INFO DAGScheduler: Submitting ResultStage 4 (MapPartitionsRDD[14] at jdbc at NativeMethodAccessorImpl.java:0), which has no missing parents
[2024-06-28T15:12:08.928+0000] {docker.py:436} INFO - 24/06/28 15:12:08 INFO MemoryStore: Block broadcast_2 stored as values in memory (estimated size 54.4 KiB, free 434.3 MiB)
[2024-06-28T15:12:08.945+0000] {docker.py:436} INFO - 24/06/28 15:12:08 INFO MemoryStore: Block broadcast_2_piece0 stored as bytes in memory (estimated size 24.6 KiB, free 434.3 MiB)
[2024-06-28T15:12:08.949+0000] {docker.py:436} INFO - 24/06/28 15:12:08 INFO BlockManagerInfo: Added broadcast_2_piece0 in memory on localhost:33565 (size: 24.6 KiB, free: 434.4 MiB)
[2024-06-28T15:12:08.952+0000] {docker.py:436} INFO - 24/06/28 15:12:08 INFO SparkContext: Created broadcast 2 from broadcast at DAGScheduler.scala:1585
[2024-06-28T15:12:08.956+0000] {docker.py:436} INFO - 24/06/28 15:12:08 INFO DAGScheduler: Submitting 1 missing tasks from ResultStage 4 (MapPartitionsRDD[14] at jdbc at NativeMethodAccessorImpl.java:0) (first 15 tasks are for partitions Vector(0))
[2024-06-28T15:12:08.957+0000] {docker.py:436} INFO - 24/06/28 15:12:08 INFO TaskSchedulerImpl: Adding task set 4.0 with 1 tasks resource profile 0
[2024-06-28T15:12:08.969+0000] {docker.py:436} INFO - 24/06/28 15:12:08 INFO TaskSetManager: Starting task 0.0 in stage 4.0 (TID 2) (localhost, executor driver, partition 0, NODE_LOCAL, 8180 bytes)
[2024-06-28T15:12:08.975+0000] {docker.py:436} INFO - 24/06/28 15:12:08 INFO Executor: Running task 0.0 in stage 4.0 (TID 2)
[2024-06-28T15:12:08.985+0000] {docker.py:436} INFO - 24/06/28 15:12:08 INFO BlockManagerInfo: Removed broadcast_0_piece0 on localhost:33565 in memory (size: 8.3 KiB, free: 434.4 MiB)
[2024-06-28T15:12:09.018+0000] {docker.py:436} INFO - 24/06/28 15:12:09 INFO BlockManagerInfo: Removed broadcast_1_piece0 on localhost:33565 in memory (size: 7.6 KiB, free: 434.4 MiB)
[2024-06-28T15:12:09.077+0000] {docker.py:436} INFO - 24/06/28 15:12:09 INFO ShuffleBlockFetcherIterator: Getting 1 (4.2 KiB) non-empty blocks including 1 (4.2 KiB) local and 0 (0.0 B) host-local and 0 (0.0 B) push-merged-local and 0 (0.0 B) remote blocks
[2024-06-28T15:12:09.081+0000] {docker.py:436} INFO - 24/06/28 15:12:09 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 15 ms
[2024-06-28T15:12:09.107+0000] {docker.py:436} INFO - 24/06/28 15:12:09 INFO CodeGenerator: Code generated in 21.105169 ms
[2024-06-28T15:12:09.131+0000] {docker.py:436} INFO - 24/06/28 15:12:09 INFO CodeGenerator: Code generated in 16.419796 ms
[2024-06-28T15:12:09.156+0000] {docker.py:436} INFO - 24/06/28 15:12:09 INFO CodeGenerator: Code generated in 14.678008 ms
[2024-06-28T15:12:09.168+0000] {docker.py:436} INFO - 24/06/28 15:12:09 INFO ShuffleBlockFetcherIterator: Getting 1 (1475.0 B) non-empty blocks including 1 (1475.0 B) local and 0 (0.0 B) host-local and 0 (0.0 B) push-merged-local and 0 (0.0 B) remote blocks
[2024-06-28T15:12:09.169+0000] {docker.py:436} INFO - 24/06/28 15:12:09 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 2 ms
[2024-06-28T15:12:09.185+0000] {docker.py:436} INFO - 24/06/28 15:12:09 INFO CodeGenerator: Code generated in 15.254191 ms
[2024-06-28T15:12:09.200+0000] {docker.py:436} INFO - 24/06/28 15:12:09 INFO CodeGenerator: Code generated in 10.992485 ms
[2024-06-28T15:12:09.218+0000] {docker.py:436} INFO - 24/06/28 15:12:09 INFO CodeGenerator: Code generated in 13.780568 ms
[2024-06-28T15:12:09.256+0000] {docker.py:436} INFO - 24/06/28 15:12:09 INFO CodeGenerator: Code generated in 33.834575 ms
[2024-06-28T15:12:10.602+0000] {docker.py:436} INFO - 24/06/28 15:12:10 INFO CodeGenerator: Code generated in 33.557558 ms
[2024-06-28T15:12:10.702+0000] {docker.py:436} INFO - 24/06/28 15:12:10 ERROR Executor: Exception in task 0.0 in stage 4.0 (TID 2)
java.sql.BatchUpdateException: Batch entry 0 INSERT INTO silver_grocery_purchase ("id","item_name","date_of_purchase","cost","quantity","purchased_by","payment_method","purchased_category") VALUES (92,'Coffee Maker','2023-01-16 +00'::date,'80.00',1,'Mother','Cash','Electric') was aborted: ERROR: duplicate key value violates unique constraint "silver_grocery_purchase_pkey"
  Detail: Key (id)=(92) already exists.  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:148)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2179)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:479)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:835)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1556)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:751)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:902)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:901)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1039)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1039)
	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2438)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
	at org.apache.spark.scheduler.Task.run(Task.scala:141)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "silver_grocery_purchase_pkey"
  Detail: Key (id)=(92) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
	... 20 more
[2024-06-28T15:12:10.758+0000] {docker.py:436} INFO - 24/06/28 15:12:10 WARN TaskSetManager: Lost task 0.0 in stage 4.0 (TID 2) (localhost executor driver): java.sql.BatchUpdateException: Batch entry 0 INSERT INTO silver_grocery_purchase ("id","item_name","date_of_purchase","cost","quantity","purchased_by","payment_method","purchased_category") VALUES (92,'Coffee Maker','2023-01-16 +00'::date,'80.00',1,'Mother','Cash','Electric') was aborted: ERROR: duplicate key value violates unique constraint "silver_grocery_purchase_pkey"
  Detail: Key (id)=(92) already exists.  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:148)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2179)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:479)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:835)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1556)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:751)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:902)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:901)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1039)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1039)
	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2438)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
	at org.apache.spark.scheduler.Task.run(Task.scala:141)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "silver_grocery_purchase_pkey"
  Detail: Key (id)=(92) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
	... 20 more
[2024-06-28T15:12:10.760+0000] {docker.py:436} INFO - 24/06/28 15:12:10 ERROR TaskSetManager: Task 0 in stage 4.0 failed 1 times; aborting job
[2024-06-28T15:12:10.761+0000] {docker.py:436} INFO - 24/06/28 15:12:10 INFO TaskSchedulerImpl: Removed TaskSet 4.0, whose tasks have all completed, from pool
[2024-06-28T15:12:10.768+0000] {docker.py:436} INFO - 24/06/28 15:12:10 INFO TaskSchedulerImpl: Cancelling stage 4
[2024-06-28T15:12:10.770+0000] {docker.py:436} INFO - 24/06/28 15:12:10 INFO TaskSchedulerImpl: Killing all running tasks in stage 4: Stage cancelled: Job aborted due to stage failure: Task 0 in stage 4.0 failed 1 times, most recent failure: Lost task 0.0 in stage 4.0 (TID 2) (localhost executor driver): java.sql.BatchUpdateException: Batch entry 0 INSERT INTO silver_grocery_purchase ("id","item_name","date_of_purchase","cost","quantity","purchased_by","payment_method","purchased_category") VALUES (92,'Coffee Maker','2023-01-16 +00'::date,'80.00',1,'Mother','Cash','Electric') was aborted: ERROR: duplicate key value violates unique constraint "silver_grocery_purchase_pkey"
  Detail: Key (id)=(92) already exists.  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:148)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2179)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:479)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:835)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1556)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:751)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:902)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:901)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1039)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1039)
	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2438)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
	at org.apache.spark.scheduler.Task.run(Task.scala:141)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "silver_grocery_purchase_pkey"
  Detail: Key (id)=(92) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
	... 20 more

Driver stacktrace:
[2024-06-28T15:12:10.774+0000] {docker.py:436} INFO - 24/06/28 15:12:10 INFO DAGScheduler: ResultStage 4 (jdbc at NativeMethodAccessorImpl.java:0) failed in 1.869 s due to Job aborted due to stage failure: Task 0 in stage 4.0 failed 1 times, most recent failure: Lost task 0.0 in stage 4.0 (TID 2) (localhost executor driver): java.sql.BatchUpdateException: Batch entry 0 INSERT INTO silver_grocery_purchase ("id","item_name","date_of_purchase","cost","quantity","purchased_by","payment_method","purchased_category") VALUES (92,'Coffee Maker','2023-01-16 +00'::date,'80.00',1,'Mother','Cash','Electric') was aborted: ERROR: duplicate key value violates unique constraint "silver_grocery_purchase_pkey"
  Detail: Key (id)=(92) already exists.  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:148)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2179)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:479)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:835)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1556)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:751)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:902)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:901)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1039)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1039)
	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2438)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
	at org.apache.spark.scheduler.Task.run(Task.scala:141)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "silver_grocery_purchase_pkey"
  Detail: Key (id)=(92) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
	... 20 more

Driver stacktrace:
[2024-06-28T15:12:10.777+0000] {docker.py:436} INFO - 24/06/28 15:12:10 INFO DAGScheduler: Job 2 failed: jdbc at NativeMethodAccessorImpl.java:0, took 1.908092 s
[2024-06-28T15:12:11.127+0000] {docker.py:436} INFO - Traceback (most recent call last):
  File "/opt/bitnami/spark/scripts/spark_silver_layer.py", line 75, in <module>
[2024-06-28T15:12:11.128+0000] {docker.py:436} INFO - write_to_postgres()
  File "/opt/bitnami/spark/scripts/spark_silver_layer.py", line 71, in write_to_postgres
    silver_load(df,spark)
  File "/opt/bitnami/spark/scripts/spark_silver_layer.py", line 63, in silver_load
[2024-06-28T15:12:11.128+0000] {docker.py:436} INFO - df.write.jdbc(POSTGRES_URL, "silver_grocery_purchase", "append", properties=POSTGRES_PROPERTIES)
  File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 1984, in jdbc
  File "/opt/bitnami/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2024-06-28T15:12:11.129+0000] {docker.py:436} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
[2024-06-28T15:12:11.129+0000] {docker.py:436} INFO - File "/opt/bitnami/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2024-06-28T15:12:11.130+0000] {docker.py:436} INFO - py4j.protocol.Py4JJavaError
[2024-06-28T15:12:11.174+0000] {docker.py:436} INFO - : An error occurred while calling o50.jdbc.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 4.0 failed 1 times, most recent failure: Lost task 0.0 in stage 4.0 (TID 2) (localhost executor driver): java.sql.BatchUpdateException: Batch entry 0 INSERT INTO silver_grocery_purchase ("id","item_name","date_of_purchase","cost","quantity","purchased_by","payment_method","purchased_category") VALUES (92,'Coffee Maker','2023-01-16 +00'::date,'80.00',1,'Mother','Cash','Electric') was aborted: ERROR: duplicate key value violates unique constraint "silver_grocery_purchase_pkey"
  Detail: Key (id)=(92) already exists.  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:148)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2179)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:479)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:835)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1556)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:751)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:902)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:901)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1039)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1039)
	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2438)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
	at org.apache.spark.scheduler.Task.run(Task.scala:141)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "silver_grocery_purchase_pkey"
  Detail: Key (id)=(92) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
	... 20 more

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2856)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGSchedu
[2024-06-28T15:12:11.174+0000] {docker.py:436} INFO - ler.scala:2792)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2791)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2791)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1247)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1247)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1247)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3060)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2994)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2983)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:989)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2398)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2419)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2438)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2463)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$1(RDD.scala:1039)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:410)
	at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:1037)
	at org.apache.spark.sql.Dataset.$anonfun$foreachPartition$1(Dataset.scala:3514)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.sql.Dataset.$anonfun$withNewRDDExecutionId$1(Dataset.scala:4309)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
	at org.apache.spark.sql.Dataset.withNewRDDExecutionId(Dataset.scala:4307)
	at org.apache.spark.sql.Dataset.foreachPartition(Dataset.scala:3514)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.saveTable(JdbcUtils.scala:901)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:70)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:48)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:75)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:73)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:84)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:107)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:107)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:98)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:461)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(origin.scala:76)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:461)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:32)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:437)
	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:98)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:85)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:83)
	at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:142)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:859)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:388)
	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:361)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:248)
	at org.apache.spark.sql.DataFrameWriter.jdbc(DataFrameWriter.scala:756)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO silver_grocery_purchase ("id","item_name","date_of_purchase","cost","quantity","purchased_by","payment_method","purchased_category") VALUES (92,'Coffee Maker','2023-01-16 +00'::date,'80.00',1,'Mother','Cash','Electric') was aborted: ERROR: duplicate key value violates unique constraint "silver_grocery_purchase_pkey"
  Detail: Key (id)=(92) already exists.  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:148)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2179)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:479)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:835)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1556)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:751)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:902)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:901)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1039)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1039)
	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2438)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
	at org.apache.spark.scheduler.Task.run(Task.scala:141)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	... 1 more
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "silver_grocery_purchase_pkey"
  Detail: Key (id)=(92) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
	... 20 more

2024-06-28 15:12:11,172:close:INFO:Closing down clientserver connection
[2024-06-28T15:12:11.240+0000] {docker.py:436} INFO - 24/06/28 15:12:11 INFO SparkContext: Invoking stop() from shutdown hook
[2024-06-28T15:12:11.240+0000] {docker.py:436} INFO - 24/06/28 15:12:11 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2024-06-28T15:12:11.253+0000] {docker.py:436} INFO - 24/06/28 15:12:11 INFO SparkUI: Stopped Spark web UI at http://localhost:4040
[2024-06-28T15:12:11.268+0000] {docker.py:436} INFO - 24/06/28 15:12:11 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2024-06-28T15:12:11.287+0000] {docker.py:436} INFO - 24/06/28 15:12:11 INFO MemoryStore: MemoryStore cleared
[2024-06-28T15:12:11.289+0000] {docker.py:436} INFO - 24/06/28 15:12:11 INFO BlockManager: BlockManager stopped
[2024-06-28T15:12:11.295+0000] {docker.py:436} INFO - 24/06/28 15:12:11 INFO BlockManagerMaster: BlockManagerMaster stopped
[2024-06-28T15:12:11.299+0000] {docker.py:436} INFO - 24/06/28 15:12:11 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2024-06-28T15:12:11.310+0000] {docker.py:436} INFO - 24/06/28 15:12:11 INFO SparkContext: Successfully stopped SparkContext
[2024-06-28T15:12:11.311+0000] {docker.py:436} INFO - 24/06/28 15:12:11 INFO ShutdownHookManager: Shutdown hook called
[2024-06-28T15:12:11.313+0000] {docker.py:436} INFO - 24/06/28 15:12:11 INFO ShutdownHookManager: Deleting directory /tmp/spark-6afb22e5-0383-4e47-b38c-9de2fc15e535
[2024-06-28T15:12:11.317+0000] {docker.py:436} INFO - 24/06/28 15:12:11 INFO ShutdownHookManager: Deleting directory /tmp/spark-970adcec-2054-4be3-9c7d-32429543ac87/pyspark-45d4e262-0914-4a91-8e9e-9ddb45f58b09
[2024-06-28T15:12:11.324+0000] {docker.py:436} INFO - 24/06/28 15:12:11 INFO ShutdownHookManager: Deleting directory /tmp/spark-970adcec-2054-4be3-9c7d-32429543ac87
[2024-06-28T15:12:11.624+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T15:12:11.644+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 265, in _raise_for_status
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://docker-proxy:2375/v1.45/containers/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 371, in _run_image
    return self._run_image_with_mounts([*self.mounts, tmp_mount], add_tmp_variable=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 398, in _run_image_with_mounts
    self.container = self.cli.create_container(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 439, in create_container
    return self.create_container_from_config(config, name, platform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 456, in create_container_from_config
    return self._result(res, True)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 271, in _result
    self._raise_for_status(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 267, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 400 Client Error for http://docker-proxy:2375/v1.45/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /tmp/airflowtmpthqvix97")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 509, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 380, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 444, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2024-06-28T15:12:11.659+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Stage_1, task_id=run_silver_job, run_id=manual__2024-06-28T15:11:01.900256+00:00, execution_date=20240628T151101, start_date=20240628T151154, end_date=20240628T151211
[2024-06-28T15:12:11.684+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 442 for task run_silver_job (Docker container failed: {'StatusCode': 1}; 190)
[2024-06-28T15:12:11.720+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-28T15:12:11.772+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T15:12:11.779+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
